
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./portfolio-app
      dockerfile: Dockerfile
    expose:
      - "${ANGULAR_PORT}"
    ports:
      - "${ANGULAR_PORT}:${ANGULAR_PORT}"
    volumes:
      - ./portfolio-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:${ANGULAR_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - portfolio-network

  backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose:
      - "${BACKEND_PORT}"
    volumes:
      - ./portfolio-backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:${BACKEND_PORT}/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    networks:
      - portfolio-network
    restart: always

volumes:
  nginx_logs:

networks:
  portfolio-network:
    driver: bridge 